name: file_logs
description: A file logger which utilizes "logging" package. The logger is very
  flexible, providing ability for the user to change the log format, log file
  name, and to override record handler to provide custom handling. For example,
  besides writing to a file, logs can be sent to a remote server.
version: 1.0.2
homepage: https://github.com/elvedin-hamzagic/file-logs
repository: https://github.com/elvedin-hamzagic/file-logs
issue_tracker: https://github.com/elvedin-hamzagic/file-logs/issues
documentation: https://github.com/elvedin-hamzagic/file-logs/wiki
license: MIT

environment:
  sdk: ^3.7.2

dependencies:
  intl: ^0.20.2
  logging: ^1.3.0
  path: ^1.9.1
  synchronized: ^3.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
