name: file_logging
description: A file logger which utilizes "logging" package.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  intl: ^0.20.2
  logging: ^1.3.0
  path: ^1.9.1
  synchronized: ^3.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
