name: file_logs
description: A file logger which utilizes "logging" package.
version: 1.0.0
homepage: https://github.com/elvedin-hamzagic/file-logs
repository: https://github.com/elvedin-hamzagic/file-logs
issue_tracker: https://github.com/elvedin-hamzagic/file-logs/issues
documentation: https://github.com/elvedin-hamzagic/file-logs/wiki
license: MIT

environment:
  sdk: ^3.8.1

dependencies:
  intl: ^0.20.2
  logging: ^1.3.0
  path: ^1.9.1
  synchronized: ^3.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
